# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   app.session:
      class: symfony\component\HttpFoundation\Session\Session
      callMethod: 'start'

   app.cart.adapter:
      class: ecommarg\cart\SessionAdapter
      arguments: ['@app.session']

   app.cart:
      class: ecommarg\cart\Cart
      arguments: ['@app.cart.adapter']
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
